import { Hero } from './hero';

export const HEROES: Hero[] = [
  { id: 12, name: 'Iron Man',
    superPower: 'Genius-level intellect, multiple powered armor suits, ability to fly',
    imageUrl: ''},
  { id: 13, name: 'Wolverine',
    superPower: 'Reflexes, retractable bone claws, regeneration, indestructible skeleton',
    imageUrl: ''},
  { id: 14, name: 'Scarlet Witch',
    superPower: 'Telekinesis, telepathy, teleportation',
    imageUrl: '' },
  { id: 15, name: 'Rocket',
    superPower: 'Enhanced strength, speed, super intelligent',
    imageUrl: '' },
  { id: 16, name: 'Vision',
    superPower: 'Superhuman, master combatant, mental & computer interaction, energy blast',
    imageUrl: '' },
  { id: 17, name: 'Hulk',
    superPower: 'Strength, speed, stamina, durability',
    imageUrl: '' },
  { id: 18, name: 'Loki',
    superPower: 'mastery of magic and illusion, energy projection, shapeshifting',
    imageUrl: '' },
  { id: 19, name: 'Captain Marvel',
    superPower: 'resistant to most toxins, energy absorption and manipulation',
    imageUrl: '' },
  { id: 20, name: 'Doctor Strange',
    superPower: 'levitation, telekinesis, hypnotism, jumps through dimensions',
    imageUrl: '' }
];
